[username]
disabled = false
format = "[](fg:overlay)[ 󰧱 $user ]($style)[](fg:overlay)"
show_always = true
style_root = "bg:overlay fg:iris"
style_user = "bg:overlay fg:iris"

format = """
$c \ 
$elixir \ 
$elm \ 
$golang \ 
$haskell \ 
$java \ 
$julia \ 
$nodejs \ 
$nim \ 
$rust \ 
$scala \ 
$python \ 
$username \  [󱞪](fg:iris)
"""
