
[java]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[ $version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[nodejs]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[󰎙 $version]($style)[](fg:overlay) "
disabled = false
symbol = "󰎙 "

[julia]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[ $version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[scala]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[ $version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[nim]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[󰆥 $version]($style)[](fg:overlay) "
disabled = false
symbol = "󰆥 "

[c]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[ $version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[python]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[ $version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[haskell]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[ $version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[elixir]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[ $version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[elm]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[ $version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[rust]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[ $version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[golang]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[ $version]($style)[](fg:overlay) "
disabled = false
symbol = " "


[username]
disabled = false
format = "[](fg:overlay)[ 󰧱 $user ]($style)[](fg:overlay)"
show_always = true
style_root = "bg:overlay fg:iris"
style_user = "bg:overlay fg:iris"

format = """
$c 
$elixir 
$elm 
$golang 
$haskell 
$java 
$julia 
$nodejs 
$nim 
$rust 
$scala 
$python 
$username  [󱞪](fg:iris)
"""
